config/routes.rb
Rails.application.routes.draw do
  resources :flights, only: [:index]
  resources :bookings, only: [:show, :new, :create]
  root "flights#index"
end

app/models/airport.rb
class Airport < ApplicationRecord
  has_many :departing_flights,
    class_name: "Flight",
    foreign_key: "start_airport_id",
    inverse_of: "from_airport"
  has_many :arriving_flights,
    class_name: "Flight",
    foreign_key: "finish_airport_id",
    inverse_of: "to_airport"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flight
  has_many :passengers

  accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :from_airport, class_name: "Airport", foreign_key: "start_airport_id"
  belongs_to :to_airport, class_name: "Airport", foreign_key: "finish_airport_id"

  has_many :bookings

  # def self.search(from_query, to_query)
  #   if from_query && to_query
  #     from_airport = Airport.find_by(code: from_query)
  #     to_airport = Airport.find_by(code: to_query)
  #     if from_airport && to_airport
  #       self.where(from_airport: from_airport.id, to_airport: to_airport.id)
  #     else
  #       Flight.all
  #     end
  #   else
  #     Flight.all
  #   end
  # end
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  belongs_to :booking
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def show
    @booking = Booking.find(params[:id])
    @flight = Flight.find(@booking.flight_id)
    @passengers = @booking.passengers
    @from_airport = @flight.from_airport.code
    @to_airport = @flight.to_airport.code
  end

  def new
    @flight = Flight.find(params[:picked_flight])
    @num_of_passengers = params[:num_of_passengers]
    @booking = Booking.new
    @num_of_passengers.to_i.times do
      @booking.passengers.build
    end
  end

  def create
    @booking = Booking.new(booking_params)
    @user = @booking.passengers.first

    if @booking.save
      PassengerMailer.with(user: @user).welcome_email.deliver_now
      redirect_to booking_path(@booking)
    else
      render "new"
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:flight_id, :num_of_passengers, passengers_attributes: [:name, :email])
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    @flights = Flight.where(["start_airport_id = ? and finish_airport_id = ?",
                             params[:from_query],
                             params[:to_query]])
    @passenger_array = [["1", 1], ["2", 2], ["3", 3], ["4", 4]]
    @departure_date = Flight.distinct.pluck(:start_datetime)
  end

  def flight_params
    params.require(:flight).permit(:start_airport_id,
                                   :finish_airport_id,
                                   :start_datetime,
                                   :flight,
                                   :from_query,
                                   :to_query)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/new.html.erb
<h1>BOOKING</h1>
<hr>
<%= params %>

<h3>Flight details:</h3>
<p> From: <%= @flight.from_airport.code %> </p>
<p> To: <%= @flight.to_airport.code %> </p>
<p> Date: <%= @flight.start_datetime %> </p>
<p> Duration: <%= @flight.flight_duration_in_seconds %> </p>
<p> Number of passengers: <%= params[:num_of_passengers] %> </p>

<hr>

<h2>Passenger details:</h2>

<%= form_with(model: @booking, local: true) do |f| %>
  <%= f.hidden_field :flight_id, value: @flight.id %>
  <%= f.hidden_field :num_of_passengers, value: @num_of_passengers %>

  <%= f.fields_for :passengers do |passenger| %>
    <%= passenger.label :name %><br>
    <%= passenger.text_field :name %><br>
    <%= passenger.label :email %><br>
    <%= passenger.email_field :email %><br>
    <br>
  <% end %>

  <%= f.submit %>
<% end %>

app/views/bookings/show.html.erb
<h1>Booking details:</h1>
<hr>
<%= @flight %>
<%= @booking %>
<%= @passengers %>
<br>
<%= link_to 'Index', root_path %>
<hr>
<h2>Flight details:</h2>
<p> Flight from: <%= @from_airport %> </p>
<p> Flight to: <%= @to_airport %> </p>
<p> Flight date: <%= @flight.start_datetime %> </p>
<p> Flight duration in seconds: <%= @flight.flight_duration_in_seconds %> </p>

<h2>Passengers:</h2>
<% @passengers.each do |passenger| %>
  <p> Name: <%= passenger.name %> </p>
  <p> Email: <%= passenger.email %> </p>
  <p> **** </p>
<% end %>

app/views/flights/index.html.erb
<h1>Flights Booker</h1>
<hr>
<%= params %>

<h2>Dropdown menus:</h2>
<%= form_with(url: "/flights", method: "get", local: true) do %>
  <p>
    <%= label_tag(:from_query, "Departing airport:") %>
    <%= select_tag(:from_query,
   options_from_collection_for_select(Airport.all, :id, :code))%>
  </p>
  <p>
    <%= label_tag(:to_query, "Arriving airport:") %>
    <%= select_tag(:to_query,
   options_from_collection_for_select(Airport.all, :id, :code))%>
  </p>
  <p>
    <%= label_tag(:num_of_passengers, "Number of passengers:") %>
    <%= select_tag(:num_of_passengers,
   options_for_select(@passenger_array))%>
  </p>
  <p>
    <%= label_tag(:departure_date, "Departure date:") %>
    <%= select_tag(:departure_date, options_for_select(@departure_date) ) %>
  </p>
  <%= submit_tag("Search") %>
<% end %>


<h3>Available flights:</h3>
<%= form_with(url: new_booking_path, method: "get", local: true) do %>
  <% @flights.each do |flight| %>
    <p>********</p>
    <p> From: <%= flight.from_airport.code %> </p>
    <p> To: <%= flight.to_airport.code %> </p>
    <p> Date: <%= flight.start_datetime %> </p>
    <p> Duration: <%= flight.flight_duration_in_seconds %> </p>
    <%= radio_button_tag(:picked_flight, flight.id) %>
    <%= label_tag(:picked_flight, "Pick this flight") %>
    <%= hidden_field_tag(:num_of_passengers, params[:num_of_passengers]) %>
  <% end %>
  <p> <%= submit_tag("Proceed") %> </p>
<% end %>

<hr>
<p>
  <%= params[:num_of_passengers] %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinFlightBooker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>